### ISSUE TITLE
Is it possible to set USE NEAREST MIPMAP FILTER on the fly?

### ISSUE THREAD

**Issue by Saitodepaula** [Calinou/godot-sponza#73]
As the title says, would it be possible to include mipmap filter setting during runtime?

**Comment by Calinou** [comment]
There's no method to do this at run-time, so I'm afraid it can't be changed without restarting the project. (To do this when restarting the project, you'll have to get Godot to read a [project settings override](https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-application-config-project-settings-override) file.)

Also, support questions are better asked on one of Godot's [community channels](https://godotengine.org/community), rather than here :slightly_smiling_face:

**Comment by Saitodepaula** [comment]
Ok, thanks. Sorry for asking here, it's just that I couldn't find this information (specifically about mipmap filter) anywhere else, and I think your demo is the only one available with this example.
